name: Sync Labels

on:
  workflow_dispatch:

jobs:
  labels:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Check labels configuration
        run: |
          echo "Checking labels configuration..."
          if [ -f ".github/labels.yml" ]; then
            echo "Labels configuration found"
            echo "Number of labels defined: $(grep -c '^[a-zA-Z]' .github/labels.yml || echo '0')"
          else
            echo "Warning: No labels configuration file found"
          fi

      - name: Sync repository labels
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync complete
        run: |
          echo ""
          echo "Label synchronization completed successfully!"
          echo "Repository labels have been updated to match the configuration."
